
services:
  traefik:
    image: traefik:v3.0
    container_name: wharftales_traefik
    command:
      - "--api.dashboard=false"
      - "--api.insecure=false"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure-alt.address=:8443"
      - "--certificatesresolvers.letsencrypt.acme.email=info@giodc.com"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.letsencrypt-dns.acme.dnschallenge=true"
      - "--certificatesresolvers.letsencrypt-dns.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.letsencrypt-dns.acme.dnschallenge.delaybeforecheck=0"
      - "--certificatesresolvers.letsencrypt-dns.acme.email=info@giodc.com"
      - "--certificatesresolvers.letsencrypt-dns.acme.storage=/letsencrypt/acme-dns.json"
      # Access logs
      - "--accesslog=true"
      - "--accesslog.format=json"
      # Metrics
      - "--metrics.prometheus=true"
      - "--metrics.prometheus.addEntryPointsLabels=true"
      - "--metrics.prometheus.addServicesLabels=true"
      - "--metrics.prometheus.addRoutersLabels=true"
      - "--entrypoints.metrics.address=:9090"
      - "--metrics.prometheus.entrypoint=metrics"
    ports:
      - "80:80"
      - "443:443"
      - "8443:8443"  # Alternative HTTPS port for dashboard
    env_file:
      - ./data/traefik-dns.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./ssl:/letsencrypt
      - ./logs/traefik:/var/log
    restart: unless-stopped
    networks:
      - wharftales

  web-gui:
    build:
      context: ./gui
      args:
        DOCKER_GID: 988
    container_name: wharftales_gui
    ports:
      - "9000:80"  # Dashboard accessible on port 9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker:ro
      - /usr/local/bin/docker-compose:/usr/local/bin/docker-compose:ro
      - ./data:/app/data
      - ./ssl:/app/ssl
      - ./apps:/app/apps
      - ./docker-compose.yml:/opt/wharftales/docker-compose.yml
      - ./VERSION:/var/www/html/../VERSION:ro
      - ./.git:/var/www/html/../.git:ro
      # Mount GUI files for live updates (development)
      - ./gui:/var/www/html
    environment:
      - DB_PATH=/app/data/database.sqlite

    
    
    labels:
      - traefik.enable=true
      - traefik.http.routers.webgui.rule=Host(`dashboard.local.wharftales.org`)
      - traefik.http.routers.webgui.entrypoints=web
      - traefik.http.services.webgui.loadbalancer.server.port=80
    networks:
      - wharftales
    restart: unless-stopped

  db:
    image: mariadb:latest
    container_name: wharftales_db
    environment:
      - MYSQL_ROOT_PASSWORD=wharftales_root_pass
      - MYSQL_DATABASE=wharftales
      - MYSQL_USER=wharftales
      - MYSQL_PASSWORD=wharftales_pass
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d
    networks:
      - wharftales
    restart: unless-stopped

volumes:
  db_data:

networks:
  wharftales:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
